name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x # Puedes poner la versión específica de Deno que uses

      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          path: ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/import_map.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install dependencies
        run: deno cache --unstable --import-map=import_map.json # Si usas import_map

      - name: Run tests
        run: deno test --unstable --allow-net --allow-env --allow-read --allow-write
